name: Update gist with new hitokoto

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: f94b970e4d184a2168a20e18bdf8febe
      CATEGORY: a
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out
      uses: actions/checkout@v2

    - name: Update gist
      run: go run .
